//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Buvarruha.java
//  @ Date : 2020. 03. 19.
//  @ Author : 
//
// test

/**
 * A Buvarruha osztaly, buvarruha felelossegeit valositja meg.
 */
public class Buvarruha extends Dolog {

	/**
	 * Buvarruha hasznalatat vegzi el.
	 * Jelen esetben nincs hatasa.
	 * @param k A karakter aki, a burvarruhat hasznalja.
	 * @param irany Melyik iranyban kivanja hasznalni a dolgot (jelen esetben nem hasznaljuk).
	 * @return boolean Minden esetben false ertekkel ter vissza (lasd korabbi feladatokban leiras).
	 */
	public boolean hasznal(Karakter k, int irany) {

		/* Aktualis metodus nevenek kiirasa debug / tesztek celjabol! */
		log("Most a <" + getClass() + "> Osztaly <" + new Throwable().getStackTrace()[0].getMethodName() + "> fuggvenye fut! ");

		kiir("karakter_hasznalt_buvarruha", "output.txt");

		return false;
	}
}
