//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Eszkimo.java
//  @ Date : 2020. 03. 19.
//  @ Author : 
//
//



/**
 * Az Eszkimo osztaly felelossegeit valositja meg.
 */
public class Eszkimo extends Karakter {

	/**
	 * Eszkimo kepessegenek hasznalata, azaz iglu epitese.
	 * @param irany Melyik iranyban hasznalja a kepesseget.
	 */
	@Override
	public void kepesseg(int irany) {

		/* Aktualis metodus nevenek kiirasa debug / tesztek celjabol! */
		log("Most a <" + getClass() + "> Osztaly <" + new Throwable().getStackTrace()[0].getMethodName() + "> fuggvenye fut! ");

		/* Leker egy szomszedos tablat (a lekert tablara fog epitkezni), valasztasi lehetoseggel, ezert true. */
		Tabla tabla_valasztott = tabla.szomszedLeker(true, irany);

		/* Ellenorzi, hogy kapott-e vissza tablat, mert ha nem akkor az azt jelenti, hogy a mezo hataran van a jatekos. */
		if(tabla_valasztott == null){
			kiir("kepesseghasznal_sikertelen","output.txt");

		/* Ellenkezo esetben hasznalja a kepesseget, es ezaltal kevesebb munkat fog tudni elvegezni a jovoben. */
		} else if(tabla_valasztott.getClass() != new Viz().getClass()){
			tabla_valasztott.igluEpit();
			setMunka(getMunka()-1);
			return;
		}
		else kiir("iglu_nem_epitheto", "output.txt");
	}

	/**
	 * Visszadja az eszkimo maximalis hp-jat.
	 * @return int Az eszkimo maximalis hp-ja.
	 */
	@Override
	protected int getMaxHp(){

		/* Aktualis metodus nevenek kiirasa debug / tesztek celjabol! */
		log("Most a <" + getClass() + "> Osztaly <" + new Throwable().getStackTrace()[0].getMethodName() + "> fuggvenye fut! ");

		return 5;
	}
}
