//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Etel.java
//  @ Date : 2020. 03. 19.
//  @ Author : 
//
//



/**
 * Az Etel osztaly felelossegeit valositja meg.
 */
public class Etel extends Dolog {

	/**
	 * Etel hasznalatat (=eves) vegzi el, hp novelese 1-gyel,
	 * amennyiben a testho nem max ertekkel rendelkezik.
	 * @param k A karakter aki, az etelt hasznalja.
	 * @param irany Melyik iranyban kivanja hasznalni a dolgot (jelen esetben nem hasznaljuk).
	 * @return boolean Minden esetben false ertekkel ter vissza (lasd korabbi feladatokban leiras).
	 */
	@Override
	public boolean hasznal(Karakter k, int irany) {

		/* Aktualis metodus nevenek kiirasa debug / tesztek celjabol! */
		log("Most a <" + getClass() + "> Osztaly <" + new Throwable().getStackTrace()[0].getMethodName() + "> fuggvenye fut! ");

		/* Eggyel no a HP-ja a karakternek. */
		k.hpValtoztat(1);
		k.getDolgok().remove(this);
		kiir("karakter_hasznalt_etel", "output.txt");

		return false;
	}
}
