//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Lapat.java
//  @ Date : 2020. 03. 19.
//  @ Author : 
//
//



/**
 * A Lapat osztaly felelossegeit valositja meg.
 */
public class Lapat extends Dolog {

	/**
	 * Lapat hasznalata - asas.
	 * @param k A karakter, aki a dolgot hasznalja.
	 * @param irany Melyik iranyban kivanja hasznalni a dolgot.
	 * @return boolean Minden esetben false ertekkel ter vissza (lasd korabbi feladatokban leiras).
	 */
	@Override
	public boolean hasznal(Karakter k, int irany) {
		/* Aktualis metodus nevenek kiirasa debug / tesztek celjabol! */
		log("Most a <" + getClass() + "> Osztaly <" + new Throwable().getStackTrace()[0].getMethodName() + "> fuggvenye fut! ");

		/* Lapattal ket egysegnyi havat lehet ellapatolni. */
		int i = 2;
		kiir("karakter_hasznalt_lapat", "output.txt");
		while(i > 0){
			k.as();
			i--;
		}
		return false;
	}
}
