//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PisztolyAlkatresz.java
//  @ Date : 2020. 03. 19.
//  @ Author : 
//
//


/**
 * PisztolyAlkatresz osztaly felelossegeit valositja meg
 */
public class PisztolyAlkatresz extends Dolog implements JatekVezerlo {

	/**
	 * Pisztoly hasznal (=elsut).
	 * @param k A karakter, aki a dolgot hasznalja.
	 * @param irany Melyik iranyban kivanja hasznalni a dolgot (jelen esetben ezt nem hasznaljuk).
	 * @return boolean Ha a pisztoly osszeszerelese es elsutese sikeres volt, akkor true ertekkel ter vissza,
	 * minden mas esetben az ertek false.
	 */
	@Override
	public boolean hasznal(Karakter k, int irany) {
		/* Aktualis metodus nevenek kiirasa debug / tesztek celjabol! */
		log("Most a <" + getClass() + "> Osztaly <" + new Throwable().getStackTrace()[0].getMethodName() + "> fuggvenye fut! ");

		/* Talalt pisztoly alkatreszek szama a tablan. */
		int alkatreszdb = 0;

		/* Vegig nezi a tablan levo osszes karakter, osszes dolgat, hogy azok kozul hany pisztoly alkatresz van. */
		for (Karakter ka : k.getTabla().getKarakterek()) {
			for (Dolog d : ka.getDolgok()) {
				if (hasonlit(d)) {
					alkatreszdb++;
					/* Ha meg van mind a harom, elsul a pisztoly. */
					if (alkatreszdb == 3){
						kiir("karakter_hasznalt_pisztolyalkatresz","output.txt");
						kiir("jatek_vege_nyert","output.txt");
						return true;
					}
				}
			}
		}
		kiir("karakter_hasznal_pisztolyalkatresz","output.txt");
		return false;
	}
}
